### PR TITLE
0.1.3

### PR DESCRIPTION
**Pull request by jonschlinkert**
@es128 please review. If you're good with the the changes, one of us can bump and publish.

### CODE REVIEW

**Comment by es128** [comment]
Changes appear quite minor. LGTM

**Comment by es128** [comment]
I'm not an `npm owner` of this, so couldn't publish, but maybe that's for the best... I realized right after I tried to do it that I should bring up a minor workflow point and let you decide how you want to handle it.

What I'd suggest you consider is that package.json version bumps be kept out of PRs in order that you can have nice isolated version bump commits like https://github.com/es128/anymatch/commit/253d2ad42f644ed18557f561312a7f8426daca84. It's true that this is redundant with git tags, but sometimes these are nice to see anyway as a visual demarcation when just skimming through a commit history.

It's a little arbitrary as setting the tag at a commit that says 

> Merge pull request #3 from jonschlinkert/0.1.3

isn't much worse, but I thought it was worth mentioning so you could decide on your preference.

**Comment by jonschlinkert** [comment]
> package.json version bumps be kept out of PRs

makes sense. I'll try to remember to do that going forward. If I don't it'll be from habit - but this is a new habit I'd like to have so don't feel bad reminding me. I'll fix npm

**Comment by jonschlinkert** [comment]
done, added to npm

**Comment by es128** [comment]
ok great... I added a meaningless commit (just to get the 0.1.3 in there without rebasing) and published

**Comment by jonschlinkert** [comment]
much appreciated

**Pull request merged**
