### PR TITLE
Fix jonschlinkert/micromatch#60

### LINKED ISSUE #60: [:punct:] expanded incorrectly
`[:punct:]` is changed to ``[!"#$%&\'()\\*+,-./:;<=>?@[\\]^_`{|}~]`` [here](https://github.com/jonschlinkert/micromatch/blob/17f06276a9a1fc8858582612d73aec5abf8744c6/lib/expand.js#L117) and because it starts with `[!` it's changed to the negated version [right after](https://github.com/jonschlinkert/micromatch/blob/17f06276a9a1fc8858582612d73aec5abf8744c6/lib/expand.js#L122). I suppose the most simple fix would be changing order of the characters in the regex class.

### PR DESCRIPTION
**Pull request by MartinKolarik**
This fixes jonschlinkert/micromatch#60 and also another issue - `,-.` was being interpreted as a range, since `-` was unescaped in the middle of the class.

There's one more problem I found, which I'm not sure how to fix. The question mark in this pattern is turned to `[^\/]` by micromatch, because micromatch expects `?` to be escaped as `%~`. However, we can't, obviously, replace `?` by `%~` right here, as that would make output of expand-braces incorrect.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Travis failing, as there's no `.travis.yml` for the repo.

**Comment by jonschlinkert** [comment]
> The question mark in this pattern is turned to [^\/] by micromatch, because micromatch expects

I have an idea of how to fix that. 

thanks for this!

**Comment by jonschlinkert** [comment]
published and released as 0.1.5. thanks again!

**Comment by jonschlinkert** [comment]
btw, thanks for reminding me about `.travis.yml`

**Pull request merged**
